# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-12 18:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20190713_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 13, 0, 17, 50, 317440)),
        ),
    ]
