# Generated by Django 2.2.3 on 2019-07-24 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20190724_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 24, 16, 8, 4, 208485)),
        ),
    ]
