# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-12 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_room', models.CharField(max_length=20)),
                ('food_type', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('mobileno', models.IntegerField()),
            ],
        ),
    ]
