# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-12 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelmgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='number_of_rooms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
